uploads = []
generated = []

[[outputs]]
id = "8gGXTrDsAoSnx4hJHAAwq"
uri = "file://manifest.xml"
type = "unspecified"
title = "SniperSheet — manifest.xml (جاهز للتثبيت)"

[[outputs]]
id = "nm0h7WLtAlOJ-pHKZoHAc"
uri = "file://SniperSheet-Guide.pdf"
type = "pdf"
title = "SniperSheet Guide — Professional Brochure (7 Pages)"
